# Uncomment the next line to define a global platform for your project
plugin 'cocoapods-binary'
install! 'cocoapods',
         :integrate_targets => false
platform :ios, '10.0'
# Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
target 'gmamts' do  
  # Pods for gmamts
  pod 'GoogleMobileAdsMediationTestSuite', :binary => true
end
